spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/renew_tecobrary?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: luffy
    password: 159456
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 34785251855bdf649025
            clientSecret: 1e641eb1355f0e1e5fe66e6c0f95a48ff2a565dc
            redirectUri: http://localhost:5000
            scope:
              - user:email
jwt-auth:
  secret: test
  expire: 86400000 # 하루
  redirectUri:
    - http://localhost:5000/oauth2/redirect

server:
  port: 9090
  servlet:
    session:
      persistent: false
      timeout: 0
  error:
    whitelabel:
      enabled: false

naver:
  client_id: a
  client_secret: a

slackbot:
  host: http://localhost:5000

github:
  user:
    client_id: clientId
    client_secret: clientSecret
    redirect_uri: redirectUrl
  api:
    scope: scope

jwt:
  secret: test