spring:
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/renew_tecobrary?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: luffy
    password: 159456
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 927946133902-m6n3vijo0jl56990mdeivag6qarfi3b5.apps.googleusercontent.com
            clientSecret: Jqi-ye7xCeXNOMCINKicYnmm
            scope:
              - profile
              - email

server:
  port: 8989

naver:
  client_id: a
  client_secret: a

slackbot:
  host: http://localhost:5000

github:
  user:
    client_id: a
    client_secret: a
    redirect_uri: http://localhost:8081/auth
  manager:
    client_id: a
    client_secret: a
    redirect_uri: http://localhost:8082
  api:
    scope: USER

jwt:
  secret: test
